mgcp_transcoding_test: Add LIBOSMOABIS_CFLAGS
Currently, we see the following failure:

make[3]: Entering directory '/build/openbsc/tests/mgcp'
  CC       mgcp_transcoding_test.o
  CC       mgcp_test.o
In file included from ../../include/openbsc/gsm_data.h:176:0,
                 from mgcp_transcoding_test.c:14:
../../include/openbsc/gsm_data_shared.h:21:35: fatal error: osmocom/abis/e1_input.h: No such file or directory
 #include <osmocom/abis/e1_input.h>
                                   ^
compilation terminated.

as gsm_data.h includes gsm_data_shared.h, which includes the e1_input.h
from libosmo-abis, we need to list libosmo-abis in the CFLAGS.

Change-Id: I27c25adfc6ee2c6f07315f3bc76fa7a70202ac4d