HACK: update osmo-mss to current master
... still, tons of unresolved symbols while linking that need to be
resolved:

undefined reference to `bsc_api_init'
undefined reference to `calc_initial_idx'
undefined reference to `rsl_ipacc_mdcx_to_rtpsock'
undefined reference to `bsc_handover_pending'
undefined reference to `rsl_ipacc_mdcx_to_rtpsock'
undefined reference to `gsm48_tx_mm_serv_ack'
undefined reference to `rsl_ipacc_mdcx'
undefined reference to `rsl_ipacc_mdcx_to_rtpsock'
undefined reference to `rsl_ipacc_mdcx_to_rtpsock'
undefined reference to `gsm0808_assign_req'
undefined reference to `rsl_ipacc_mdcx'
undefined reference to `rsl_ipacc_mdcx'
undefined reference to `gsm48_tx_mm_serv_rej'
undefined reference to `gsm48_handle_paging_resp'
undefined reference to `gsm48_tx_mm_serv_rej'
undefined reference to `send_siemens_mrpci'
undefined reference to `gsm48_tx_mm_serv_rej'
undefined reference to `gsm0808_assign_req'
undefined reference to `rsl_ipacc_mdcx'
undefined reference to `tall_fle_ctx'
undefined reference to `tall_paging_ctx'