gsm0408_dispatch: Fix uninitialized var warning
Got this warning since my upgrade to gcc 8.1.0. Quick check tells me
it's probably a false positive, but let's fix the warning anyway.

openbsc/openbsc/src/libmsc/gsm_04_08.c: In function ‘gsm0408_dispatch’:
openbsc/openbsc/src/libmsc/gsm_04_08.c:1260:5: error: ‘res_len’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  if (res_len != 4) {
     ^
openbsc/openbsc/src/libmsc/gsm_04_08.c:1223:10: note: ‘res_len’ was declared here
  uint8_t res_len;
          ^~~~~~~

Change-Id: Ifa45f73645c9ab022c18a012abe03214aa21526f